### ISSUE TITLE
java.lang.RuntimeException: java.util.concurrent.ExecutionException

### ISSUE THREAD

**Issue by wupoclaa** [biovoxxel/bv3dbox#6]
Hi,

Whenever I try to use the Voronoi threshold labeler (or any other option of the Biovoxxel 3D plug in) an exception occurs:
[Exception.txt](https://github.com/biovoxxel/bv3dbox/files/11477240/Exception.txt)

I work in a server with the following characteristics:

Operating System: CentOS Stream 9                 
       CPE OS Name: cpe:/o:centos:centos:9
        Kernel: Linux 5.14.0-200.el9.x86_64
      Architecture: x86-64
   Hardware Vendor: Dell Inc.
    Hardware Model: PowerEdge R650

I use the latest version of ImageJ and have activated the updates sites:
    bv3dbox
    clij
    clij2
    clijx-assistant
    clijx-assistant-extensions
    3D ImageJ Suite

Any idea what the problem might be?

**Comment by biovoxxel** [comment]
Hm, difficult to say. The error comes up in the actual GUI part, so I am not sure if it is a problem because you try to run it headless on the server. But that is just a guess. If you do this via a IJ macro for example that should still work.
The update site setup is fine.
It seems to have no clij2 instance. If there is no graphics unit (NVIDIA graphics card) or any GPU that can be used, this might not work since the Voronoi Threshold Labeler is based on all the GPU-accellerated methods from CLIJ2.

**Comment by wupoclaa** [comment]
#If there is no graphics unit (NVIDIA graphics card) or any GPU that can be used, this might not work since the Voronoi Threshold Labeler is based on all the GPU-accellerated methods from CLIJ2.#

Ok, so that's the problem...

Thank you!
